on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
    - uses: actions/checkout@v3

    - name: install azure cli
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Azure Cloud Set AzureUSGovernment
      run: az cloud set --name AzureUSGovernment
      
    - name: Azure Login with Managed Identity
      run: az login --identity
           
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache-dependency-path: test/package-lock.json
        cache: 'npm'
           
    - name: Install Botium
      run: |
          pushd 'test'
          npm install
          popd

    - name: Run Botium Tests
      run: |
          cd test
          npm run mocha

